//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM_Post
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public string PostContent { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
